//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchenik
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public decimal ClassID { get; set; }
        public string Number { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
