USE [master]
GO

/****** Object:  Database [school]    Script Date: 11.06.2017 21:46:32 ******/
CREATE DATABASE [school]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'school', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MEGAHYPER\MSSQL\DATA\school.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'school_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MEGAHYPER\MSSQL\DATA\school_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [school] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [school].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [school] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [school] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [school] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [school] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [school] SET ARITHABORT OFF 
GO

ALTER DATABASE [school] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [school] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [school] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [school] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [school] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [school] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [school] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [school] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [school] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [school] SET  DISABLE_BROKER 
GO

ALTER DATABASE [school] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [school] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [school] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [school] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [school] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [school] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [school] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [school] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [school] SET  MULTI_USER 
GO

ALTER DATABASE [school] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [school] SET DB_CHAINING OFF 
GO

ALTER DATABASE [school] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [school] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [school] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [school] SET  READ_WRITE 
GO

